//! The registry re-parses every archive with JavaScript libraries and compares the result with the
//! metadata the tool declared. These fixtures hold the Worker's output (generated by
//! registry/scripts/metadata-fixtures.mjs); the tool must produce byte-identical canonical JSON.

use ppr_tool::canonical::canonical_string;
use ppr_tool::metadata::parse_package_metadata;
use ppr_tool::names::Format;
use serde_json::Value;
use std::path::Path;

#[test]
fn metadata_matches_the_registry_parser() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures");
    let mut failures = Vec::new();
    let mut count = 0;
    for format in Format::ALL {
        let mut cases: Vec<_> = std::fs::read_dir(root.join(format.as_str())).unwrap().map(|e| e.unwrap().path()).collect();
        cases.sort();
        for dir in cases {
            count += 1;
            let label = format!("{format}/{}", dir.file_name().unwrap().to_string_lossy());
            let meta: Value = serde_json::from_str(&std::fs::read_to_string(dir.join("case.json")).unwrap()).unwrap();
            let kind = meta["kind"].as_str().unwrap();
            let file = std::fs::read_dir(&dir)
                .unwrap()
                .map(|e| e.unwrap().path())
                .find(|p| {
                    let name = p.file_name().unwrap().to_string_lossy().to_lowercase();
                    !name.ends_with("case.json") && name != "expected.json"
                })
                .unwrap();
            let text = std::fs::read_to_string(&file).unwrap();
            let text = text.strip_prefix('\u{feff}').unwrap_or(&text);
            let expected =
                std::fs::read_to_string(dir.join("expected.json")).unwrap_or_else(|_| panic!("{label}: run node registry/scripts/metadata-fixtures.mjs"));
            match (kind, parse_package_metadata(format, text)) {
                ("ok", Ok(metadata)) => {
                    let actual = canonical_string(&Value::Object(metadata));
                    if actual != expected.trim_end() {
                        failures.push(format!("{label}: canonical JSON differs\n  tool:     {actual}\n  registry: {}", expected.trim_end()));
                    }
                }
                ("ok", Err(error)) => failures.push(format!("{label}: tool rejected a valid file: {}", error.message)),
                ("server-error" | "client-only-error", Ok(_)) => failures.push(format!("{label}: tool accepted a file it must reject ({kind})")),
                ("server-error" | "client-only-error", Err(_)) => {}
                (other, _) => failures.push(format!("{label}: unknown kind {other}")),
            }
        }
    }
    assert!(count >= 40, "fixtures present");
    assert!(failures.is_empty(), "{}", failures.join("\n"));
}
